"""create_table_cash

Revision ID: ca40f76feb65
Revises: 99758a91301d
Create Date: 2025-11-28 22:14:38.151065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca40f76feb65'
down_revision: Union[str, Sequence[str], None] = '99758a91301d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cash',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('cash_type', sa.Enum('coin', 'bill', name='cashtype'), nullable=False),
        sa.Column('cash', sa.Integer, nullable=True),
        sa.Column('stock', sa.Integer, nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now(), nullable=False),
        sa.Column('created_by', sa.Integer, nullable=True),
        sa.Column('updated_at', sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
        sa.Column('updated_by', sa.Integer, nullable=True),
        sa.Column('deleted_at', sa.DateTime, nullable=True),
        sa.Column('deleted_by', sa.Integer, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cash')

    # ### end Alembic commands ###
